controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#route employes
employe_new:
    path: /employe/new
    controller: App\Controller\EmployeController::new
employe_show:
    path: /employe/{id}
    controller: App\Controller\EmployeController::show
employe_edit:
    path: /employe/{id}/edit
    controller: App\Controller\EmployeController::edit

#route bureau
bureau_new:
    path: /bureau/new
    controller: App\Controller\BureauController::new
bureau_show:
    path: /bureau/{id}
    controller: App\Controller\BureauController::show
bureau_edit:
    path: /bureau/{id}/edit
    controller: App\Controller\BureauController::edit

#route bse
bse_new:
    path: /bse/new
    controller: App\Controller\BseController::new
bse_show:
    path: /bse/{id}
    controller: App\Controller\BseController::show
bse_edit:
    path: /bse/{id}/edit
    controller: App\Controller\BseController::edit