controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#route user
user_new:
    path: /user/new
    controller: App\Controller\UserController::new
user_show:
    path: /user/{id}
    controller: App\Controller\UserController::show
user_edit:
    path: /user/{id}/edit
    controller: App\Controller\UserController::edit
user_edit_missionaire:
    path: /user/{id}/editmissionnaire
    controller: App\Controller\UserController::editmissionnaire


#route bureau
bureau_new:
    path: /bureau/new
    controller: App\Controller\BureauController::new
bureau_show:
    path: /bureau/{id}
    controller: App\Controller\BureauController::show
bureau_edit:
    path: /bureau/{id}/edit
    controller: App\Controller\BureauController::edit

#route bse:bon de saisie des engagements
bse_new:
    path: /bse/new
    controller: App\Controller\BseController::new
bse_show:
    path: /bse/{id}
    controller: App\Controller\BseController::show
bse_edit:
    path: /bse/{id}/edit
    controller: App\Controller\BseController::edit
bse_valide:
    path: /bse/{id}/valide
    controller: App\Controller\BseController::valide
bse_show_missionnaire:
    path: /bse_missionnaire/{id}
    controller: App\Controller\BseController::showMissionnaire
bse_edit_missionnaire:
    path: /bse/{id}/editMissionnaire
    controller: App\Controller\BseController::editMissionnaire
bse_edit_missionnaire_Avec_Bst:
    path: /bse/{id}/editMissionnaireAvecBst
    controller: App\Controller\BseController::editMissionnaireAvecBst
succes_index:
    path: /succes
    controller: App\Controller\BseController::succes

#route bst:bon spécial de transport
bst_new:
    path: /bst/new
    controller: App\Controller\BstController::new
bst_edit:
    path: /bst/{id}/edit
    controller: App\Controller\BstController::edit
bst_paye:
    path: /bst/{id}/paye
    controller: App\Controller\BstController::paye
bst_new_or:
    path: /bst/new
    controller: App\Controller\BstController::new
bst_service:
    path: /bst/newService
    controller: App\Controller\BstController::newService


#route vers OR:Ordre de route
ordreRoute_new:
    path: /ordreRoute/new
    controller: App\Controller\OrdreRouteController::new
ordreRoute_new_missionnaire:
    path: /ordreRoute/new_missionnaire
    controller: App\Controller\OrdreRouteController::new_missionnaire
ordreRoute_edit:
    path: /ordreRoute/{id}/edit
    controller: App\Controller\OrdreRouteController::edit
OrdreRoute_paye:
    path: /ordreRoute/{id}/paye
    controller: App\Controller\PaymentController::paye

#route vers payement
payement_index:
    path: /payment/index
    controller: App\Controller\PaymentController::index
payment_new:
    path: /payment/new
    controller: App\Controller\PaymentController::new
payment_show:
    path: /payment/{id}
    controller: App\Controller\PaymentController::show
payment_edit:
    path: /payment/{id}/edit
    controller: App\Controller\PaymentController::edit
payment_bst:
    path: /payment/{id}/bst
    controller: App\Controller\PaymentController::bst

#route vers credit
credit_new:
    path: /credit/new
    controller: App\Controller\CreditController::new
credit_show:
    path: /credit/{id}
    controller: App\Controller\CreditController::show
credit_edit:
    path: /credit/{id}/edit
    controller: App\Controller\CreditController::edit

#route depart
depart_new:
    path: /depart/new
    controller: App\Controller\DepartController::new
depart_show:
    path: /depart/{id}
    controller: App\Controller\DepartController::show
depart_edit:
    path: /depart/{id}/edit
    controller: App\Controller\DepartController::edit
depart_index:
    path: /depart/
    controller: App\Controller\DepartController::index
depart_delete:
    path: /depart/{id}/delete
    controller: App\Controller\DepartController::delete