controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#route employes
employe_new:
    path: /employe/new
    controller: App\Controller\EmployeController::new
employe_show:
    path: /employe/{id}
    controller: App\Controller\EmployeController::show
employe_edit:
    path: /employe/{id}/edit
    controller: App\Controller\EmployeController::edit

#route bureau
bureau_new:
    path: /bureau/new
    controller: App\Controller\BureauController::new
bureau_show:
    path: /bureau/{id}
    controller: App\Controller\BureauController::show
bureau_edit:
    path: /bureau/{id}/edit
    controller: App\Controller\BureauController::edit

#route bse:bon de saisie des engagements
bse_new:
    path: /bse/new
    controller: App\Controller\BseController::new
bse_show:
    path: /bse/{id}
    controller: App\Controller\BseController::show
bse_edit:
    path: /bse/{id}/edit
    controller: App\Controller\BseController::edit

#route bst:bon spécial de transport
bst_new:
    path: /bst/new
    controller: App\Controller\BstController::new
bst_show:
    path: /bst/{id}
    controller: App\Controller\BstController::show
bst_edit:
    path: /bst/{id}/edit
    controller: App\Controller\BstController::edit


#route vers OR:Ordre de route
ordreRoute_new:
    path: /ordreRoute/new
    controller: App\Controller\OrdreRouteController::new
ordreRoute_show:
    path: /ordreRoute/{id}
    controller: App\Controller\OrdreRouteController::show
ordreRoute_edit:
    path: /ordreRoute/{id}/edit
    controller: App\Controller\OrdreRouteController::edit

#route vers payement
payment_new:
    path: /payment/new
    controller: App\Controller\paymentController::new
payment_show:
    path: /payment/{id}
    controller: App\Controller\paymentController::show
payment_edit:
    path: /payment/{id}/edit
    controller: App\Controller\paymentController::edit